<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Blog

add_action('genesis_sidebar', 'lcm_do_latest_author_box', 9);
function lcm_do_latest_author_box(){

    // arguments, adjust as needed
    $args = array(
        'post_type'      => 'post',
        'post_status'    => 'publish',
        'posts_per_page' => 1,
        'order' => 'DESC',
        'orderby' => 'date',
        'tax_query' => array(
            array(
                'taxonomy' => 'category',
                'field' => 'slug',
                'terms' => array('featured', 'article'),
                'operator' => 'NOT IN'
            )
        )
    );

    $latest_post_author_id = null;

    /*
    Overwrite $wp_query with our new query.
    The only reason we're doing this is so the pagination functions work,
    since they use $wp_query. If pagination wasn't an issue,
    use: https://gist.github.com/3218106
    */
    global $wp_query;
    $wp_query = new WP_Query( $args );

    if ( have_posts() ) :
        while ( have_posts() ) : the_post();
            $latest_post_author_id = get_the_author_meta('ID');
        endwhile;
    endif;

    wp_reset_query();

    $author_meta = get_user_meta($latest_post_author_id);
    if ($author_meta['description'][0] != '') {
        echo '<div class="sidebar-post-author row">';
        echo '<div class="author-heading col-sm-12">';
        echo '<h4>Contributing Writers</h4>';
        echo '<h3>' . $author_meta['first_name'][0] . ' ' . $author_meta['last_name'][0] . ' | ' . $author_meta['headline'][0] . '</h3>';
        echo '</div>';
        echo '<div class="col-sm-12">';
        echo get_wp_user_avatar($latest_post_author_id, 96, 'right');
        echo lcm_limit_words($author_meta['description'][0], null, null, true);
        echo '<a href="'. get_author_posts_url($latest_post_author_id) .'" class="read-more icon icon-circle-arrow-right">Read More</a>';
        echo '</div>';
        //echo '<div class="col-sm-4">';
        //echo '</div>';
        echo '</div>';
    }
}


add_action('genesis_before_loop', 'lcm_blog_latest');
function lcm_blog_latest(){

    $paged = get_query_var( 'paged' );

    if($paged != 0){
        return;
    }

    // arguments, adjust as needed
    $args = array(
        'post_type'      => 'post',
        'post_status'    => 'publish',
        'posts_per_page' => 1,
        'order' => 'DESC',
        'orderby' => 'date',
        'tax_query' => array(
            array(
                'taxonomy' => 'category',
                'field' => 'slug',
                'terms' => array('featured', 'article'),
                'operator' => 'NOT IN'
            )
        )
    );

    /*
    Overwrite $wp_query with our new query.
    The only reason we're doing this is so the pagination functions work,
    since they use $wp_query. If pagination wasn't an issue,
    use: https://gist.github.com/3218106
    */
    global $wp_query;
    $wp_query = new WP_Query( $args );

    if ( have_posts() ) :
        echo '<h1 class="entry-title">Latest Blog Posts</h1>';
        echo '<div class="row latest-blog-post entry-content">';
        while ( have_posts() ) : the_post();

            echo '<div class="col-sm-12 entry-thumbnail">';
            echo '<a href="'. get_permalink(get_the_ID()) .'">';
            echo get_the_post_thumbnail(get_the_ID(), 'large');
            echo '</a>';
            echo '</div>';
            echo '<div class="col-sm-12 entry-header">';
            echo '<div class="col-sm-6 col-xs-12">';
            echo '<h3 class="entry-title"><a href="'. get_permalink() .'">' . get_the_title() . '</a></h3>';
            echo '</div>';
            echo '<div class="col-sm-6 col-xs-12 entry-date">';
            echo 'Post by  '. get_the_author() .' | '. get_the_date() ;
            echo '</div>';
            echo '</div>';
            echo '<div class="col-sm-12 entry-content">'. lcm_excerpt(get_the_content(), 100, ' ...', true) .'</div>';

        endwhile;
        echo '</div>';
    endif;

    wp_reset_query();
}

function lcm_blog_loop() {
    global $post;

    $paged = get_query_var( 'paged' );

    $first_page_post_count = 2;
    $subsequent_pages_post_count = 10;
    $paged = $paged ? $paged : 1;

    if($paged > 1){
        // not first page
        $posts_per_page = $subsequent_pages_post_count;

        if($paged == 2){
            // second page
            $offset = $first_page_post_count + 1;
        } else {
            // subsequent pages
            $offset = $first_page_post_count + ($subsequent_pages_post_count * ($paged - 2)) + 1;
        }

    } else {
        // first page
        $offset = 1;
        $posts_per_page = $first_page_post_count;
    }

    //$paged = $paged - 1;
    //var_dump($paged);
    //var_dump(get_query_var( 'paged' ));

	// arguments, adjust as needed
	$args = array(
		'post_type'      => 'post',
		'post_status'    => 'publish',
		'posts_per_page' => $posts_per_page,
		'offset' => $offset,
        'order' => 'DESC',
        'orderby' => 'date',
        'tax_query' => array(
            array(
                'taxonomy' => 'category',
                'field' => 'slug',
                'terms' => array('featured', 'article'),
                'operator' => 'NOT IN'
            )
        )
	);

	/* 
	Overwrite $wp_query with our new query.
	The only reason we're doing this is so the pagination functions work,
	since they use $wp_query. If pagination wasn't an issue, 
	use: https://gist.github.com/3218106
	*/
	global $wp_query;
	$wp_query = new WP_Query( $args );

    //var_dump($wp_query);
    //var_dump(have_posts());

	if ( have_posts() ) : 
		echo '<div class="row blog-list">';
		while ( have_posts() ) : the_post();

            echo '<div class="col-sm-12 row">';
            echo '<div class="col-sm-4  col-xs-12">';
            echo '<a href="'. get_permalink(get_the_ID()) .'">';
            echo get_the_post_thumbnail(get_the_ID(), 'large');
            echo '</a>';
            echo '</div>';
            echo '<div class="col-sm-8 col-xs-12">';
			echo '<h3 class="entry-title"><a href="'. get_permalink() .'">' . get_the_title() . '</a></h3>';
            echo '<div class="entry-date">';
            echo 'Post by  '. get_the_author() .' | '. get_the_date() ;
            echo '</div>';
            echo '<div class="entry-content">';
            echo lcm_excerpt(get_the_content(), 25, true);
            echo '</div>';
            echo '</div>';
            echo '</div>';

		endwhile;
		echo '</div>';

		//do_action( 'genesis_after_endwhile' );
        $big = 999999999; // need an unlikely integer

        echo '<div class="pagination">';
        $pagination_args = array(
            'base' => str_replace( $big, '%#%', get_pagenum_link( $big ) ),
            'format' => '?paged=%#%',
            'current' => max( 1, $paged ),
            'type' => 'plain'
        );

        // Take the number of found posts and subtract 3 to account for the 3 on the blog landing
        // Take the remaining count and divide by 10 and round up to get the remaining page count
        $remaining_posts = $wp_query->found_posts - 3;
        $remaining_posts = ceil($remaining_posts / 10);
        $remaining_posts = $remaining_posts + 1;
        $pagination_args['total'] = $remaining_posts;

        echo paginate_links( $pagination_args );
        echo '</div><!-- pagination -->';
	else:
        //echo 'There are no blog posts at this time.';
    endif;
 
	wp_reset_query();
}
add_action( 'genesis_loop', 'lcm_blog_loop' );
remove_action( 'genesis_loop', 'genesis_do_loop' );



//* The blog page loop logic is located in lib/structure/loops.php
genesis();
